apps/postulantes/urls.py
from django.urls import path
#from .views import registro_exitoso, listar_postulantes, registrar, postulante_print, 
from . import views
#from .views import ConfirmacionView
from .utils import generar_pdf


"""The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
app_name = 'postulantes'

urlpatterns = [
    path('registrar/', views.registrar, name='registrar_postulante'),
    path('exito/', views.registro_exitoso, name='registro_exitoso'),
    path('listar/', views.listar_postulantes, name='listar_postulantes'),
    path('generar_pdf/ficha/<int:pk>', views.postulante_print, name='generar_pdf' ),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admision/', include('apps.postulantes.urls'))
]

apps/postulantes/models.py
import os
from django.db import models
from gdstorage.storage import GoogleDriveStorage

gd_storage = GoogleDriveStorage()


#class Persona(models.Model):
#    """Model definition for Persona."""
#
#    # TODO: Define fields here
#    nombre = models.CharField(max_length=100)
#    apellidos = models.CharField(max_length=100)
#    dni = models.CharField(max_length=8)
#    correo = models.EmailField(max_length=254)
#    fecha_registro = models.DateTimeField(auto_now_add=True)
#
#    class Meta:
#        """Meta definition for Persona."""
#
#        verbose_name = 'Persona'
#        verbose_name_plural = 'Personas'
#
#    def __str__(self):
#        """Unicode representation of Persona."""
#        return f"{self.nombre} {self.apellidos}"


class Postulante(models.Model):
    """Model definition for Postulante."""
    GENERO_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    )
    CARRERAS_CHOICES = (
        ('C', 'Contabilidad'),
        ('EM', 'Explotación Minera'),
        ('CC', 'Construcción Civil'),
    )

    # TODO: Define fields here
    nombres = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=100)
    apellido_materno  = models.CharField(max_length=100)
    dni = models.CharField(max_length=8, unique=True)
    correo = models.EmailField()
    genero = models.CharField(max_length=1, choices=GENERO_CHOICES)
    celular = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField(auto_now=False, auto_now_add=False)
    lugar_nacimiento = models.CharField(max_length=100)
    lugar_nacimiento_distrito = models.CharField(max_length=100, verbose_name='Distrito')
    lugar_nacimiento_provincia = models.CharField(max_length=100, verbose_name = 'Provincia')
    lugar_nacimiento_departamento = models.CharField(max_length=100, verbose_name = 'Departamento')
    tutor_apellidos = models.CharField(max_length=100, blank=True)
    tutor_nombres = models.CharField(max_length=100, blank=True)
    tutor_parentesco = models.CharField(max_length=100, blank=True)
    nombre_ies = models.CharField(max_length=100)
    tipo_institucion = models.CharField(max_length=20, choices=(('Publica', 'Publica'), ('Privada', 'Privada')))
    anio_egreso = models.CharField(verbose_name = 'Año_egreso', max_length=4)
    direccion_institucion = models.CharField(max_length=255)
    institucion_distrito = models.CharField(max_length=100)
    institucion_provincia = models.CharField(max_length=100)
    institucion_departamento = models.CharField(max_length=100)
    programa_postula_primera_opcion = models.CharField(max_length=2, choices=CARRERAS_CHOICES)
    programa_postula_segunda_opcion = models.CharField(max_length=2, choices=CARRERAS_CHOICES)
    enterado_proceso_admision = models.CharField(max_length=100, verbose_name= '¿Cómo se entero del proceso de admisión?')
    codigo_voucher = models.CharField(max_length=15, unique=True)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    imagen1 = models.FileField('DNI', upload_to='maps', blank=False, null=False, storage=gd_storage)
    imagen2 = models.FileField('Certificado de Estudios', upload_to='maps', blank=False, null=False, storage=gd_storage)
    imagen3 = models.FileField('Partida de Nacimiento', upload_to='maps', blank=False, null=False, storage=gd_storage)
    imagen4 = models.FileField('Voucher', upload_to='maps', blank=False, null=False, storage=gd_storage)

    class Meta:
        """Meta definition for MODELNAME."""

        verbose_name = 'Postulante'
        verbose_name_plural = 'Postulantes'
    

    
    def __str__(self):
        """Unicode representation of MODELNAME."""
        return self.dni
    

#class Documento(models.Model):
#    """Model definition for MODELNAME."""
#    #DOCUMENTO_CHOICES = (
#    #    ('DNI', 'DNI'),
#    #    ('V', 'VOUCHER DE PAGO'),
#    #    ('CE', 'CERTIFICADO DE ESTUDIOS'),
#    #    ('PN', 'PARTIDA O CONSTANCIA DE NACIMIENTO')
#    #)
#    # TODO: Define fields here
#    postulante = models.ForeignKey(Postulante, on_delete=models.CASCADE)
#    imagen = models.ImageField(upload_to='documentos/')
#    fecha_creacion = models.DateTimeField(auto_now_add=True) # URL de la imagen en Google Drive
#    # Otros campos relevantes para la gestión de documentos del postulante
#
#    class Meta:
#        """Meta definition for MODELNAME."""
#
#        verbose_name = 'Documento'
#        verbose_name_plural = 'Documentos'
#
#    def __str__(self):
#        """Unicode representation of MODELNAME."""
#        return f"Documento de {self.postulante} ({self.fecha_creacion})"

apps/postulantes/forms.py
from django import forms
from .models import Postulante


class RegistroPostulanteForm(forms.ModelForm):
    fecha_nacimiento=forms.DateField(label='Fecha de Nacimiento',  widget=forms.TextInput(attrs={'placeholder': 'dd/mm/aaaa'}))

    class Meta:
        model = Postulante
        fields = ['nombres', 'apellido_paterno', 'apellido_materno',
                  'dni', 'correo', 'genero', 'celular', 'fecha_nacimiento',
                  'lugar_nacimiento', 'lugar_nacimiento_distrito',
                  'lugar_nacimiento_provincia', 'lugar_nacimiento_departamento',
                  'tutor_apellidos', 'tutor_nombres','tutor_parentesco',
                  'nombre_ies','tipo_institucion', 'anio_egreso', 'direccion_institucion',
                  'institucion_distrito', 'institucion_provincia', 'institucion_departamento',
                   'programa_postula_primera_opcion','programa_postula_segunda_opcion',
                    'enterado_proceso_admision', 'codigo_voucher', 'imagen1','imagen2', 'imagen3', 'imagen4' ]

templates/postulantes/email_template.html
hola mundo

templates/postulantes/listar_postulantes.html
{% extends 'base.html' %}


{% block content %}
<h1>Listado de Postulantes Registrados</h1>

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Apellido Paterno</th>
        <th scope="col">Apellido Materno</th>
        <th scope="col">Nombres</th>
        <th scope="col">Voucher Link</th>
        <th scope="col">ficha</th>
      </tr>
    </thead>
    <tbody>
    {% for postulante in postulantes %}
      <tr>
        <th scope="row">{{postulante.id}}</th>
        <td>{{postulante.apellido_paterno}}</td>
        <td>{{postulante.apellido_materno}}</td>
        <td>{{postulante.nombres}}</td>
        <td>{{postulante.imagen4.url}}</td>
        <td> <form action="{% url 'postulantes:generar_pdf' postulante.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn-primary">Generar ficha PDF</button>
        </form></td>
        </tr>
      
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}
    
    

templates/postulantes/registrar_postulante.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container my-4">
    <div class="card">
        <div class="card-header">
            <img class="px-2 py-2" src="https://iestparib.edu.pe/wp-content/uploads/2023/08/cropped-logoweb.jpg" alt="">

            <h3 class="text-center">Formulario de Inscripción</h3>
        </div>
        <div class="card-body">
            <form action="" method="post" class="my-class" enctype="multipart/form-data"> {% csrf_token %}
                <h4 >Datos Personales</h4>
                <div class="row">
                    <div class="col-md-3">
                        {{form.dni | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.apellido_paterno | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.apellido_materno | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.nombres | as_crispy_field}}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        {{form.genero | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.celular | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.correo | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.fecha_nacimiento | as_crispy_field}}
                    </div>
                    <div class="col-md-2">
                        {{form.lugar_nacimiento | as_crispy_field}}
                    </div>
                    <div class="col-md-2">
                        {{form.lugar_nacimiento_distrito | as_crispy_field}}
                    </div>
                    <div class="col-md-2">
                        {{ form.lugar_nacimiento_provincia | as_crispy_field}}
                    </div>
                    <div class="col-md-2">
                        {{ form.lugar_nacimiento_departamento | as_crispy_field}}
                    </div>
                </div>
                <h4>Datos del padre o apoderado (llenar solo si es menor de edad)</h4>
                <div class="row">
                    <div class="col-md-4">
                        {{ form.tutor_apellidos | as_crispy_field}}
                    </div>
                    <div class="col-md-4">
                        {{ form.tutor_nombres | as_crispy_field}}
                    </div>
                    <div class="col-md-4">
                        {{ form.tutor_parentesco | as_crispy_field}}
                    </div>
                </div>
                <h4>Información Académica</h4>
                <div class="row">
                    <div class="col-md-4">
                        {{form.nombre_ies | as_crispy_field}}
                    </div>
                    <div class="col-md-4">
                        {{form.tipo_institucion | as_crispy_field}}
                    </div>
                    <div class="col-md-4">
                        {{form.anio_egreso | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.direccion_institucion | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.institucion_distrito | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.institucion_provincia | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.institucion_departamento | as_crispy_field}}
                    </div>
                </div>
                <h4>Postulación</h4>
                <div class="row">
                    <div class="col-md-4">
                        {{form.programa_postula_primera_opcion | as_crispy_field}}
                    </div>
                    <div class="col-md-4">
                        {{form.programa_postula_segunda_opcion | as_crispy_field}}
                    </div>

                    <div class="col-md-4">
                        {{form.enterado_proceso_admision | as_crispy_field}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-3"></div>
                    <div class="col-md-3">
                        <img src="https://iestparib.edu.pe/wp-content/uploads/2024/03/WhatsApp-Image-2023-04-04-at-16.01.13.jpeg" height="250" alt="">
                    </div>
                    <div class="col-md-3">
                        {{form.codigo_voucher | as_crispy_field}}
                    </div>
                </div>
                <h4>Adjuntar Documentos</h4>
                <div class="row">
                    <div class="col-md-3">
                        {{form.imagen1 | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.imagen2 | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.imagen3 | as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.imagen4 | as_crispy_field}}
                    </div>
                </div>
                <hr>
                <p>Declaro bajo juramento que los datos que consigno en la presente FICHA DE INSCRIPCIÓN, son verídicos y me remito para la confrontación con los documentos originales.  
                    De no ser correctos pierdo la vacante de admisión y renuncio a todo derecho que pueda obtener.</p>
                <hr>
                <div class="d-grid gap-2 col-6 mx-auto">
                    <button class="btn btn-primary " type="submit">Registrarse</button>
                </div>
            </form>
        </div>
    </div>
</div>
    
{% endblock content %}
    

templates/postulantes/registro_exitoso.html
{% extends 'base.html' %}

{% block title %}
    ADMISIÓN 2024
{% endblock title %}


{% block content %}
<div class="container">
    <br>
  
      <div class="col-md-offset-3">
          <div class="card text-center m-4">
              <div class="card-header">
                  <div class="d-grid gap-2">
                      <button class="btn btn-primary"><strong>Registro Satisfactorio</strong></button>  </div>
                  </div>
              <div class="card-body">
                <h5 class="card-title">Validar su inscripción</h5>
                <hr>
                <ol class="text-lg-start">
                  <li>Revisar la bandeja de entrada o <strong>SPAM</strong>  de su correo electrónico </li>
                  <li>Debe visualizar el mensaje de confirmación de inscripción por parte del correo <strong>admision@iestparib.edu.pe</strong></li>
                  <li>Se le adjunta la ficha de postulante</li>
                  <!--<li>Estaremos validando el voucher de pago mientras se genera su ficha de inscripción</li>-->
                </ol>
              </div>
              <!--<div class="card-footer text-muted"><strong>NOTA : La ficha de inscripción(.pdf) se enviara a su correo en un lapso de 10 min.</strong> </div>-->
            </div>
      </div>
  </div>
  
{% endblock content %}
    
    